version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...

      # Get AWS Account ID
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      # Variables
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=latest

      # Create ECR Repository if not exists
      - |
        aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --region $AWS_DEFAULT_REGION || \
        aws ecr create-repository --repository-name $IMAGE_REPO_NAME --region $AWS_DEFAULT_REGION

      # Login to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Building Docker image...

      # Build Docker Image
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

      # Tag Image
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...

      # Push Image
      - docker push $REPOSITORY_URI:$IMAGE_TAG
